In [2]:
import numpy as np
arr2d=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]]
    
)
print(arr2d)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
np.sum(arr2d,axis=0)#row

array([12, 15, 18])

In [4]:
np.sum(arr2d,axis=1)#column

array([ 6, 15, 24])

In [7]:
#indexing
print(arr2d[2,1])


8


In [51]:
#slicing
print(arr2d[0:2,1:3])# Extracts first 2 rows and last 2 columns
#get all row of first column
print(arr2d[0:,0:1])

[[2 3]
 [5 6]]
[[1]
 [4]
 [7]]


In [45]:
arr3d=np.array([[[1,2,3],[3,4,5],[6,7,8]],[[3,2,1],[5,4,3],[8,7,6]]])
arr3d.shape#will print depth row and column

(2, 3, 3)

In [46]:
print(arr3d[1,1,1])

4


In [60]:
#slicing in 3d array
print(arr3d[1:,1:2,1:3])
# Get the first row from each "sheet" in a 3D array
print(arr3d[:,0:1,:])

[[[4 3]]]
[[[1 2 3]]

 [[3 2 1]]]


In [64]:
#replacing element
# Replace all elements in column 1 with 0
arr3d[:,:,1:2]=0

In [65]:
print(arr3d)

[[[1 0 3]
  [3 0 5]
  [6 0 8]]

 [[3 0 1]
  [5 0 3]
  [8 0 6]]]
