In [6]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[2])#Simple Indexing
print(arr[-2])

3
8


In [13]:
#Extracting part of arrays
print(arr[0:2])#starting index and elements till 2-1
print(arr[2:5])#starting index and elements till index 5-1 i.e 4
print(arr[:3])#will assume zero itself
print(arr[1:])#will assume length itself
print(arr[::2])#will print every second element

[1 2]
[3 4 5]
[1 2 3]
[2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [17]:
sliced_view=arr[0:2]
sliced_view[0]=2
print(sliced_view)
print(arr)

[2 2]
[2 2 3 4 5 6 7 8 9]


In [21]:
#Fancy Indexing
print(arr[[0,7,4]])

[2 8 5]


In [24]:
#Boolean Masking(Filter Data)
print(arr[arr%2==0])

[2 2 4 6 8]


In [46]:
#Exercise
#Create a 3×3 array filled with random numbers and print its shape.
arr3d=np.array([[[1,2,3],[3,4,6]],[[5,6,8],[7,8,9]],[[9,10,11],[11,12,12]],[[1,2,3],[3,4,6]]])

print(arr3d.shape)
#Convert an array of floats [1.1, 2.2, 3.3] into integers.
arrf=np.array([1.1, 2.2, 3.3])
print(arrf.astype(np.int32))
#Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
arrnum=np.array([1, 2, 3, 4, 5, 6])
print(arrnum[arrnum%2==0])
#Reshape a 1D array of size 9 into a 3×3 matrix.
arr1d=np.array([1,2,3,4,5,6,7,8,9])
print(arr1d.reshape(3,3))
#Use boolean masking to filter numbers greater than 50 in an array.
arrrnad=np.array([100,2,3,4,5,99])
print(arrrnad[arrrnad>50])

(4, 2, 3)
[1 2 3]
[2 4 6]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[100  99]
