In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr**2)#this operation is called vectorization

[ 1  4  9 16 25]


In [3]:
print(arr+10)#10 is scalar value i.e brodcast to entire array

[11 12 13 14 15]


In [8]:
arr2d=np.array([[1,2],[3,4]])
arr1d=[1,5]
print(arr2d+arr1d)#1d array is brodacted to 2d array

[[2 7]
 [4 9]]


In [15]:
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])
mean=np.mean(data,axis=0)
std=np.std(data,axis=0)
normalized_data=(data-mean)/std
print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]


[7.07106781 7.07106781 7.07106781]
